### ISSUE TITLE
dont work secam

### ISSUE THREAD

**Issue by chezsick** [svofski/CRT#1]
each times i run process.py :::
Traceback (most recent call last):
  File "process.py", line 372, in <module>
    process_file(inputfiles[0])
  File "process.py", line 353, in process_file
    s.run()
  File "process.py", line 320, in run
    secam,sel = self.modulate(rgb_samples[:count], line[:count])
  File "process.py", line 271, in modulate
    self.probe_sink.work(probnik)
  File "/home/pi/CRT/SECAM/imagesink.py", line 27, in work
    self.savePng(frame)
  File "/home/pi/CRT/SECAM/imagesink.py", line 49, in savePng
    writer.write(f, rows)
  File "/usr/local/lib/python3.5/dist-packages/png.py", line 670, in write
    nrows = self.write_passes(outfile, check_rows(rows))
  File "/usr/local/lib/python3.5/dist-packages/png.py", line 704, in write_passes
    return self.write_packed(outfile, rows)
  File "/usr/local/lib/python3.5/dist-packages/png.py", line 736, in write_packed
    for i, row in enumerate(rows):
  File "/usr/local/lib/python3.5/dist-packages/png.py", line 662, in check_rows
    (vpr, len(row), i))
png.ProtocolError: ProtocolError: Expected 768 values but got 2304 value, in row 0
/usr/local/lib/python3.5/dist-packages/matplotlib/backends/backend_gtk3.py:181: Warning: Source ID 8 was not found when attempting to remove it
  GLib.source_remove(self._idle_draw_id)
/usr/local/lib/python3.5/dist-packages/matplotlib/backends/backend_gtk3.py:181: Warning: Source ID 9 was not found when attempting to remove it
  GLib.source_remove(self._idle_draw_id)
/usr/local/lib/python3.5/dist-packages/matplotlib/backends/backend_gtk3.py:181: Warning: Source ID 10 was not found when attempting to remove it
  GLib.source_remove(self._idle_draw_id)

so, i can't use this :(
please fix it

**Comment by svofski** [comment]
@chezsick does it happen on one of the test images from the repo, or is it with a different one? It looks like pypng is not happy about something in your picture, but I cannot tell what's going on from the trace alone. If you can share it, please attach to a comment here and I'll try it on my system.

**Comment by svofski** [comment]
Patience! Je viens de reproduire la même erreur dans my ubuntu. On va voir...

**Comment by svofski** [comment]
Essayez maintenant. Ça devrait marcher avec pypng 0.0.20.

**Comment by chezsick** [comment]
Ca Marche, Malgré Quelque Warning
Is Work, With few warning
All done
/usr/local/lib/python3.5/dist-packages/matplotlib/backends/backend_gtk3.py:181: Warning: Source ID 8 was not found when attempting to remove it
  GLib.source_remove(self._idle_draw_id)
/usr/local/lib/python3.5/dist-packages/matplotlib/backends/backend_gtk3.py:181: Warning: Source ID 9 was not found when attempting to remove it
  GLib.source_remove(self._idle_draw_id)
/usr/local/lib/python3.5/dist-packages/matplotlib/backends/backend_gtk3.py:181: Warning: Source ID 10 was not found when attempting to remove it

![plasma](https://user-images.githubusercontent.com/21131245/62422859-9d8d5100-b6b9-11e9-9d5c-55d3c4b8ee43.png)
![plasma](https://user-images.githubusercontent.com/21131245/62422860-a716b900-b6b9-11e9-9f4f-575b674f7c53.png)

**Comment by chezsick** [comment]
j'aimerait qu'on traite aussi les vidéo ...

**Comment by svofski** [comment]
On pourrait décomposer les vidéo en png, mais ça serait un proces un peu lent:
```
ffmpeg -i video.mp4 frame%04d.png
python3 process.py frame*.png # cela va prendre une éternité
ffmpeg -i output/frame%04d.png secam.mp4
````
Il faut penser en refaire tout cela dans une manière moins cientifique et plus pratique.

**Comment by svofski** [comment]
Une expérience: 240 images, 15 minutes environ. Ça fait 0.26fps ou ~1% de realtime.
https://youtu.be/dPDxGlBH4TQ
Je ne sais pas si cela vaut la peine. Je dirais que non. Un shader, ça irait mieux.

**Comment by chezsick** [comment]
je peut aussi traiter les gif :::::::::
![123953681_o_secam](https://user-images.githubusercontent.com/21131245/64587401-8b30c200-d39f-11e9-8298-f9b59271c6d8.gif)

**Comment by chezsick** [comment]
c'est possible que t'ajoute juste pour codé seulement et décodé seulement ?, car pour le moment j'ai juste codé puis décodé.

**Comment by svofski** [comment]
on peut, en théorie, mais a quoi bon? le resultat intermediaire est sauveguardé et on peut le voir. pour décoder un image "real", comme depuis un tv, mon algorithm n'est pas suffisaiment robuste, ça ne marcharait pas. en tous cas, c'est pas sorcier — je t'encourage à regarder le code ;)

je voudrais continuer les experiments, mais pour le moment je manque de temps vachement. en fait, je viens d'obtenir un générateur de signaux test SECAM.

**Comment by chezsick** [comment]
Je sais pas si tu connais :::::::::::::::::::: https://github.com/kFYatek/color_modem
c'est une sorte de concurrence a ton projet mais ca va peut etre t'aidé, désoler si j'etait en retard par apport a sa apparition mais j'ai pas osé sous peine de te décevoir, deja trois etoile (moi l'auteur de hacktv et un youtubeur) si ca t'interesse met une etoile.

**Comment by svofski** [comment]
ç'est merveilleux, merci ! moi, j'ai pas de temps pour ces choses-là reçemment, peut-être plus tard. une etoile de plus, vive SÉCAM ! :D

**Comment by chezsick** [comment]
j'ai fait un gist mais mis la sur github, pour générer les paramettre de cryptimage accompagné de color modem pour une chaine iptv ::::::::::::::: https://github.com/chezsick/MyGist/tree/master/iptvci pour le fun, et pour pas décevoir les russes comme les francais les `.ru` seront en secam.

j'espère que ca va t'amusé.
Avec L'IPTV, Amuse Toi Bien !
